export default class CustomConsts
{
    public static readonly COUNTRIES = [
        { sc: 'AE', name: 'United Arab Emirates' },
        { sc: 'AR', name: 'Argentina' },
        { sc: 'AT', name: 'Austria' },
        { sc: 'AU', name: 'Australia' },
        { sc: 'BE', name: 'Belgium' },
        { sc: 'BG', name: 'Bulgaria' },
        { sc: 'BO', name: 'Bolivia' },
        { sc: 'BR', name: 'Brazil' },
        { sc: 'BY', name: 'Belarus' },
        { sc: 'CA', name: 'Canada' },
        { sc: 'CH', name: 'Switzerland' },
        { sc: 'CL', name: 'Chile' },
        { sc: 'CO', name: 'Colombia' },
        { sc: 'CR', name: 'Costa Rica' },
        { sc: 'CZ', name: 'Czech Republic' },
        { sc: 'DE', name: 'Germany' },
        { sc: 'DK', name: 'Denmark' },
        { sc: 'DO', name: 'Dominican Republic' },
        { sc: 'EC', name: 'Ecuador' },
        { sc: 'EE', name: 'Estonia' },
        { sc: 'EG', name: 'Egypt' },
        { sc: 'ES', name: 'Spain' },
        { sc: 'FI', name: 'Finland' },
        { sc: 'FR', name: 'France' },
        { sc: 'GB', name: 'United Kingdom' },
        { sc: 'GR', name: 'Greece' },
        { sc: 'GT', name: 'Guatemala' },
        { sc: 'HK', name: 'Hong Kong' },
        { sc: 'HN', name: 'Honduras' },
        { sc: 'HU', name: 'Hungary' },
        { sc: 'ID', name: 'Indonesia' },
        { sc: 'IE', name: 'Ireland' },
        { sc: 'IL', name: 'Israel' },
        { sc: 'IN', name: 'India' },
        { sc: 'IS', name: 'Iceland' },
        { sc: 'IT', name: 'Italy' },
        { sc: 'JP', name: 'Japan' },
        { sc: 'KR', name: 'South Korea' },
        { sc: 'KZ', name: 'Kazakhstan' },
        { sc: 'LT', name: 'Lithuania' },
        { sc: 'LU', name: 'Luxembourg' },
        { sc: 'LV', name: 'Latvia' },
        { sc: 'MA', name: 'Morocco' },
        { sc: 'MX', name: 'Mexico' },
        { sc: 'MY', name: 'Malaysia' },
        { sc: 'NG', name: 'Nigeria' },
        { sc: 'NI', name: 'Nicaragua' },
        { sc: 'NL', name: 'Netherlands' },
        { sc: 'NO', name: 'Norway' },
        { sc: 'NZ', name: 'New Zealand' },
        { sc: 'PA', name: 'Panama' },
        { sc: 'PE', name: 'Peru' },
        { sc: 'PH', name: 'Philippines' },
        { sc: 'PK', name: 'Pakistan' },
        { sc: 'PL', name: 'Poland' },
        { sc: 'PT', name: 'Portugal' },
        { sc: 'PY', name: 'Paraguay' },
        { sc: 'RO', name: 'Romania' },
        { sc: 'SA', name: 'Saudi Arabia' },
        { sc: 'SE', name: 'Sweden' },
        { sc: 'SG', name: 'Singapore' },
        { sc: 'SK', name: 'Slovakia' },
        { sc: 'SV', name: 'El Salvador' },
        { sc: 'TH', name: 'Thailand' },
        { sc: 'TR', name: 'Turkey' },
        { sc: 'TW', name: 'Taiwan' },
        { sc: 'UA', name: 'Ukraine' },
        { sc: 'US', name: 'United States' },
        { sc: 'UY', name: 'Uruguay' },
        { sc: 'VE', name: 'Venezuela' },
        { sc: 'VN', name: 'Vietnam' },
        { sc: 'ZA', name: 'South Africa' },
    ]
}
